FROM centos:7.9.2009

LABEL maintainer="Dellear<https://github.com/Dellear>"

ENV TZ=Asia/Shanghai

RUN yum update -y \
    && DEBIAN_FRONTEND="noninteractive" yum install curl tzdata -y \
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
    && yum install pango.x86_64 libXcomposite.x86_64 libXcursor.x86_64 libXdamage.x86_64 libXext.x86_64 libXi.x86_64 libXtst.x86_64 cups-libs.x86_64 libXScrnSaver.x86_64 libXrandr.x86_64 GConf2.x86_64 alsa-lib.x86_64 atk.x86_64 gtk3.x86_64 -y \
    && curl -fsSL https://rpm.nodesource.com/setup_16.x | bash - \
    && yum install -y nodejs \
    && yum clean all

CMD ["bash"]